### ISSUE TITLE
rense fails to launch on Windows 7

### ISSUE THREAD

**Issue by maiertech** [rsense/rsense#36]
I'm using Ruby 2.1.3.0 on Windows 7 (installed via chocolatey). I installed all dependencies with bundler. 

When I launch rsense with

```
bundle exec rsense start --path ~/path/to/repo
```

I get the following error:

```
c:/tools/ruby213/lib/ruby/gems/2.1.0/gems/spoon-0.0.4/lib/spoon/windows.rb:20:in
 `<module:Spoon>': undefined method `attach_function' for Spoon:Module (NoMethod
Error)
        from c:/tools/ruby213/lib/ruby/gems/2.1.0/gems/spoon-0.0.4/lib/spoon/win
dows.rb:17:in `<top (required)>'
        from c:/tools/ruby213/lib/ruby/gems/2.1.0/gems/spoon-0.0.4/lib/spoon.rb:
16:in `require'
        from c:/tools/ruby213/lib/ruby/gems/2.1.0/gems/spoon-0.0.4/lib/spoon.rb:
16:in `<top (required)>'
        from c:/tools/ruby213/lib/ruby/gems/2.1.0/gems/rsense-0.5.18/lib/rsense/
client/runner.rb:3:in `require'
        from c:/tools/ruby213/lib/ruby/gems/2.1.0/gems/rsense-0.5.18/lib/rsense/
client/runner.rb:3:in `<top (required)>'
        from c:/tools/ruby213/lib/ruby/gems/2.1.0/gems/rsense-0.5.18/lib/rsense/
client/daemon.rb:5:in `require_relative'
        from c:/tools/ruby213/lib/ruby/gems/2.1.0/gems/rsense-0.5.18/lib/rsense/
client/daemon.rb:5:in `<top (required)>'
        from c:/tools/ruby213/lib/ruby/gems/2.1.0/gems/rsense-0.5.18/bin/rsense:
3:in `require_relative'
        from c:/tools/ruby213/lib/ruby/gems/2.1.0/gems/rsense-0.5.18/bin/rsense:
3:in `<top (required)>'
        from c:/tools/ruby213/bin/rsense:23:in `load'
        from c:/tools/ruby213/bin/rsense:23:in `<main>'
```

I wonder if anyone managed to get rsense running on Windows.

**Comment by edubkendo** [comment]
Ok I've opened an issue on spoon : https://github.com/headius/spoon/issues/17 to try to get to the bottom of it

**Comment by maiertech** [comment]
It looks like they fixed something for Windows in headius/spoon@31ccbc93fcd0b1813d0bbee8eb3db3481765fca5. I tried starting rsense against newer commit headius/spoon@970c61ce02905557c1cfe3fa3efd90452bff3f4b, but then I ran into another issue with FFI.

**Comment by maiteko** [comment]
I just added a comment to the spoon issue you created. the issue with the gem in rubygems is that it is first missing the "extend FFI::Library" line (fixed in the current version of spoon) but it is also missing the line "ffi_lib 'MSVCRT'" above the calls to _spawnve and _spawnvpe (still broken in the current version of spoon)

however once those are running rsense fails to start and throws this error:
 e:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsense-0.5.18/lib/rsense/client/runner.rb:112:in `start': uninitialized constant Spoon::FileActions (NameError)
        from e:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rsense-0.5.18/bin/rsense:12:in`<top (required)>'
        from E:/Ruby22-x64/bin/rsense:23:in `load'
        from E:/Ruby22-x64/bin/rsense:23:in`<main>'

This is probably because FileActions is not defined when it creates the windows spoon module, only when it creates the Unix spoon module. I'm not sure if this needs to be checked on your side, or implemented in spoon.

**Comment by jonyeezs** [comment]
@maiteko did you manage to fix the error on FileActions?

**Comment by maiteko** [comment]
Nope. Had to drop this and focus on more immediate tasks. Never heard back from the spoon people either.

**Comment by oca159** [comment]
I am having the same problem with rsense.
rsense start
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/lib/rsense/client/runner.rb:112:in `start': uninitialized constant Spoon::FileActions (NameError)
Did you mean?  FileUtils
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/bin/rsense:12:in `<top (required)>'
        from C:/Ruby23-x64/bin/rsense:22:in `load'
        from C:/Ruby23-x64/bin/rsense:22:in `<main>'

My spoon version es 0.0.6.
I am using windows 8. 
Any ideas?

**Comment by ahrherrera** [comment]
@oca159 Osvaldo, has encontrado la solución? Me pasa lo mismo en Windows 10. Aún no he encontrado la solución.

**Comment by mikhaelangelo** [comment]
get the same issue here.
Windows 10 64x
